### ISSUE TITLE
To-Do

### ISSUE THREAD

**Issue by Jgallig1** [Jgallig1/Homework#1]
### Part 1: Set up Overleaf

- [X] Task one: Create LaTeX document.
- [X] Task two: Insert .EPS images into LaTeX.

### Part 2:  Learning Git
- [X] Introduction Sequence
- [X] Ramping Up
- [X]  Moving Work Around
- [X] A Mixed Bag
- [X] Advanced Topics

### Part 3:  Github Issue Submission
- [x] Submit a link to this repository.
- [X] Ensure the grader has access to view the repo.
